spring:
  application:
    name: course-service

  datasource:
    url: jdbc:postgresql://localhost:5432/courseDB
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # or create, create-drop, validate as needed
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"

server:
  port: 7071

category-service:
  base:
    url: "http://category-service/api/category/"

video-service:
  base:
    url: "http://video-service/api/videos/"

eureka:
  client:
    service-url:
      defaultZone: " http://localhost:8761/eureka/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true


info:
  app:
    name: "Course service"
    description : "This is the course service"
    version : "1.0"
    author : "Utkarsh Kumar Verma"