spring:
  application:
    name: "discovery-server"


# Configuration for not to register with itself
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
server:
  port: 8761
