spring:
  application:
    name: video-service
  data:
    mongodb:
      host: localhost
      port: 27018
      database: videoDB


server:
  port: ${PORT:7078}


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: " http://localhost:8761/eureka/"
    refresh:
      enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: "Video Service"
    description : "This is a video service"
    version : "1.0"
    author : "Utkarsh Kumar Verma"


