spring:
  application:
    name: category-service
  datasource:
    url: jdbc:mysql://localhost:3305/categoryDB
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"
  cloud:
    discovery:
      client:
        simple:
          instances:
            category-service:
              - uri: http://172.31.96.1:7010
server:
  port: 7010

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
info:
  app:
    name: "Category service"
    description : "This is the category service"
    version : "1.0"
    author : "Utkarsh Kumar Verma"

