spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


server:
  port: 7075

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true


info:
  app:
    name: "Gateway Service"
    description: "This is the Gateway service"
    author : "Utkarsh Kumar Verma"